spring.datasource.url=jdbc:sqlserver://127.0.0.1:1433;databaseName=dbbotwpp;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=System@123

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

telegram.bot-token=8689893767:AAFr6Pajkm6L_WH5dJDkz0FV7ZvXM80FUm8
telegram.api-url=https://api.telegram.org