package br.com.tdm.whatsappsaldo.enums;

public enum TipoComando {
    DEFINIR_SALDO,
    REGISTRAR_GASTO,
    CONSULTAR_SALDO,
    DEFINIR_CREDITO,
    REGISTRAR_GASTO_CREDITO,
    CONSULTAR_CREDITO,
    CONSULTAR_EXTRATO,
    CONSULTAR_EXTRATO_CREDITO,
    RESUMO_GERAL,
    RESUMO_HOJE,
    RESUMO_SEMANA,
    RESUMO_MES,
    DESFAZER_ULTIMO,
    DESFAZER_SALDO,
    DESFAZER_CREDITO,
    RESETAR_SALDO_TOTAL,
    RESETAR_CREDITO_TOTAL,
    RESETAR_TOTAL_INDEFINIDO,
    RESETAR_SALDO,
    RESETAR_CREDITO,
    RESETAR_INDEFINIDO,
    AJUDA,
    VALOR_INVALIDO,
    VALOR_GASTO_ZERO,
    DESCONHECIDO
}
